name: Trigger Fork Sync

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Call fork repo dispatch event
        run: |
          curl -X POST https://api.github.com/repos/minukHwang/zerogravity-frontend/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.FORK_PAT }}" \
            -d '{"event_type": "sync-from-upstream", "client_payload": {"branch": "${{ github.ref_name }}"}}'
